### PR TITLE
Make the tests pass

### PR DESCRIPTION
**Pull request by baskerville**

### CODE REVIEW

**Comment by humenda** [comment]
Why is the change below better than its original version? I'd argue that it
actually takes two actions and costs avoidable instructions.

```
-    if path.as_ref().ends_with(".dz") {
+    if path.as_ref().extension().and_then(|ext| ext.to_str()) == Some("dz") {
```

Could you please avoid lines longer than 80 characters?

Apart from that, it looks fine, thanks!

**Comment by baskerville** [comment]
> Why is the change below better than its original version?

The original version doesn't work as intended: `Path::new("abc.dict.dz").ends_with(".dz")` returns `false`.

**Comment by humenda** [comment]
My bad, I expected it to work as `ends_with` on a str.

**Comment by baskerville** [comment]
Here's a shorter version:
```rust
    if path.as_ref().extension() == Some(OsStr::new("dz")) {
```

**Comment by humenda** [comment]
AFAIK, `OsStr` does not allocate, so please change to this :).

**Comment by baskerville** [comment]
Done.

**Comment by baskerville** [comment]
The limit on the line lengths is now enforced.

**Pull request merged**
